### ISSUE TITLE
is there an echo-server way for `.respond_with`

### ISSUE THREAD

**Issue by sassman** [LukeMathWalker/wiremock-rs#109]
Is there any way that I can pass `ResponseTemplate` to `.respond_with` that would behave like an echo http server? 

So essentially responding with the very same body back that the request did contain?

**Comment by sassman** [comment]
I think it can be done with an own impl of the `Respond` trait that mimics the echo-server behaviour, as shown in the examples.
https://docs.rs/wiremock/latest/wiremock/trait.Respond.html#dynamic-responses

**Comment by LukeMathWalker** [comment]
Yes, you should be able to do it by implementing `Respond`!

**Comment by sassman** [comment]
Thanks, works like charme.
