### ISSUE TITLE
http-types dependency seems unmaintained

### ISSUE THREAD

**Issue by jplatte** [LukeMathWalker/wiremock-rs#123]
Hi! Is it important for wiremock to use the `http-types` crate (from [http-rs](https://github.com/http-rs) which unfortunately looks pretty dead as a whole) as opposed to the `http` crate (from hyperium)? It has not seen a release in almost two years and pulls in several unwanted dependencies ([old] `serde_qs`, old `rand`).

**Comment by LukeMathWalker** [comment]
It isn't crucial, and I'd be open to removing it if somebody wants to put in the effort.

**Comment by flisky** [comment]
Well, I'll give it a try on this weekends:)
