### ISSUE TITLE
This line in the README confused me a little

### ISSUE THREAD

**Issue by asafigan** [LukeMathWalker/wiremock-rs#36]
This looks like a great project and I am really excited about trying it out.

When I read this in the README, I think I misunderstood it.
> You should use one instance of `MockServer` for each test, to ensure full isolation and no cross-test interference.

The first time I read it, I thought it meant that you could only have one `MockServer` per test. But after re-reading it, I think it means that you shouldn't share `MockServer` between multiple tests.

I think this should be re-worded to be clearer. Something like:

> To ensure full isolation and no cross-test interference, `MockServer`s shouldn't be shared between tests. Instead, `MockServer`s should be created in the test that they are used.

**Comment by LukeMathWalker** [comment]
I agree - do you want open a PR?

**Comment by asafigan** [comment]
Ok, will do.
