### ISSUE TITLE
Mock: Unclear docs

### ISSUE THREAD

**Issue by MarcoIeni** [LukeMathWalker/wiremock-rs#42]
What is `self.matches`?

https://github.com/LukeMathWalker/wiremock-rs/blob/16980ac6fbe73fc76a3741315edf096789a73c7e/src/mock.rs#L215

**Comment by LukeMathWalker** [comment]
It was from before the introduction of `ActiveMock` - it refers to `ActiveMock::matches` now: https://github.com/LukeMathWalker/wiremock-rs/blob/16980ac6fbe73fc76a3741315edf096789a73c7e/src/active_mock.rs#L23
