### ISSUE TITLE
Support tokio 1.0

### ISSUE THREAD

**Issue by wayofthepie** [LukeMathWalker/wiremock-rs#46]
With tokio 1.0 released Ive been moving things over to it. It would be good to get `wiremock` up to 1.0 too. I had a quick look, I _think_ all deps support 1.0 now except `async-std`. There is a PR for that update in `async-std` https://github.com/async-rs/async-std/pull/924. 

If this is something that you want to do I can take a look at it. Thanks.

**Comment by LukeMathWalker** [comment]
`wiremock` does not expose in any way its executor to the user, therefore it should work as is in a codebase that is using `tokio` 1.0 - did you have issues with it?

Nonetheless, updating was already on my radar (to trim to dependency tree for clients who have already migrated). 
We are not using the `tokio` compat feature for `async-std` (and it is a development dependency), so it is not blocker.

If you want to take a shot at it, go ahead 😁

**Comment by wayofthepie** [comment]
Ah you're right, I was getting a panic in the tests saying they need to run in a tokio runtime, but that was not wiremock. All is good now. I can still look at this in the next few days if no one else does, would be nice to just pull in one version. Thanks!

**Comment by LukeMathWalker** [comment]
I might get to work on this today/tomorrow - let's see 😁
