### ISSUE TITLE
Redirect on POST form submission raises Hyper IncompleteBody error

### ISSUE THREAD

**Issue by guspower** [LukeMathWalker/wiremock-rs#72]
Hi,

I'm trying to mock a service that performs a redirect on POST when given `x-www-form-urlencoded` form data. I'm using a `ureq` Agent instance to submit the form. What I observe is that the request library runs until timeout; I have created a [cut-down example that replicates the problem](https://github.com/guspower/redirect-on-post) I'm seeing.

I'm unsure whether this error is caused by my stupidity, a ureq bug, a wiremock bug or something else.

Any and all help gratefully received. 

EDIT: I've added a `warp` standalone server into the example that provides the same redirect-on-post functionality and have verified that the `ureq` client usage works with it.

**Comment by guspower** [comment]
Update: It turns out that it's caused by a bug in `ureq`, specifically that it sends the `Content-Length` header on the subsequent GET request after the POST is redirected. This tricks `hyper` into thinking there is content available and it fails on trying to retrieve it with an `UnexpectedEof`.

**Comment by LukeMathWalker** [comment]
Sorry we couldn't help, but thanks for updating with your findings - it might be useful to others!

**Comment by guspower** [comment]
No worries - [I've opened a PR against `ureq`](https://github.com/algesten/ureq/pull/394) which will hopefully fix the issue.
